# Generated by Django 6.0.4 on 2026-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_equipment_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='inventory'),
        ),
    ]
