# Generated by Django 6.0.4 on 2026-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id_cars', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=10)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
